<!--
    Do not modify this configuration file.
    Instead, you should patch this file using Coveo.CloudPlatformClient.Custom.config.
-->
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/" xmlns:coveo="http://www.sitecore.net/xmlconfig/coveo/">
  <sitecore coveo:require="!disabled">
    <pipelines>
      <!-- INDEXING REST EXCEPTIONS HANDLER
           Pipeline that handles indexing exceptions.
           
           IMPORTANT: The "indexingRestExceptionsHandler" is now deprecated. The "httpRetry.PlatformExceptionsHandler" is invoked instead.
      -->
      <indexingRestExceptionsHandler>
        <!-- WAIT AND RETRY
             Processor that retries a REST call after a specified interval.
             Supported attributes for each statusCodeGroup:

                 NumberOfRetry: Specifies the number of times the processor has to be executed for the specific group.

                 Interval: Specifies the time in milliseconds to wait before retrying the call.

                 StatusCodes: Specifies the list of HTTP status codes the group has to be executed for.
        -->
        <processor name="CoveoWaitAndRetryCloudPlatformCall" type="Coveo.CloudPlatformClientBase.Pipelines.WaitAndRetry, Coveo.CloudPlatformClientBase">
          <groups hint="list:AddStatusCodeGroup">
            <statusCodeGroup name="ThrottlingAndTimeout" type="Coveo.CloudPlatformClientBase.Pipelines.WaitAndRetryStatusCodeGroup, Coveo.CloudPlatformClientBase">
              <numberOfRetry>1000</numberOfRetry>
              <interval>3000</interval>
              <statusCodes hint="list:AddStatusCode">
                <!-- Limit exceeded or too many requests -->
                <statusCode>429</statusCode>
                <!-- Bad Gateway -->
                <statusCode>502</statusCode>
                <!-- Service Unavailable -->
                <statusCode>503</statusCode>
                <!-- Gateway Timeout -->
                <statusCode>504</statusCode>
              </statusCodes>
            </statusCodeGroup>
            <statusCodeGroup name="ServerError" type="Coveo.CloudPlatformClientBase.Pipelines.WaitAndRetryStatusCodeGroup, Coveo.CloudPlatformClientBase">
              <numberOfRetry>10</numberOfRetry>
              <interval>3000</interval>
              <statusCodes hint="list:AddStatusCode">
                <!-- Internal Server Error -->
                <statusCode>500</statusCode>
                <!-- Insufficient Storage -->
                <statusCode>507</statusCode>
                <!-- Loop Detected -->
                <statusCode>508</statusCode>
                <!-- Bandwidth Limit Exceeded -->
                <statusCode>509</statusCode>
              </statusCodes>
            </statusCodeGroup>
          </groups>
        </processor>
      </indexingRestExceptionsHandler>
      <httpRetry.PlatformExceptionsHandler>
        <processor name="CoveoWaitAndRetryPlatformCall" type="Coveo.Framework.Utils.Rest.HttpWaitAndRetry, Coveo.Framework">
          <retryGroups hint="list:AddGroup">
            <retryGroup name="TooManyPendingRefreshesForSecurityCache" type="Coveo.Framework.Utils.Rest.HttpWaitAndRetryGroup, Coveo.Framework">
              <retryStrategy type="Coveo.Framework.Utils.Rest.ConstantIntervalRetryStrategy">
                <numberOfRetry>2</numberOfRetry>
                <interval>00:00:10</interval>
              </retryStrategy>
              <conditions hint="raw:AddCondition">
                <condition requestMethods="POST" requestUriMatch="/rest/organizations/[^/]+/securitycache/refresh$" statusCodes="412" responseMatch="TOO_MANY_PENDING_REFRESHES_FOR_SECURITY_CACHE" />
              </conditions>
              <onRetriesFailureActions hint="list:AddOnRetriesFailureAction">
                <action type="Coveo.Framework.Utils.Rest.RetryActions.LogMessage, Coveo.Framework">
                  <level>INFO</level>
                  <message>The security cache could not be refreshed because another refresh is already running.</message>
                </action>
                <action type="Coveo.Framework.Utils.Rest.RetryActions.Continue, Coveo.Framework" />
              </onRetriesFailureActions>
            </retryGroup>
            <group name="ThrottlingAndTimeout" ref="coveo/retryGroups/throttlingAndTimeout" />
            <group name="ServerError" ref="coveo/retryGroups/serverError" />
          </retryGroups>
        </processor>
      </httpRetry.PlatformExceptionsHandler>
      
      <getSearchUserIdentities>
        <!-- The AddAnonymousEmailUserIdentity allows the retrieval of public documents from external sources. -->
        <processor name="AddAnonymousEmailUserIdentity" type="Coveo.CloudPlatformClient.Processors.GetSearchUserIdentities.AddAnonymousEmailUserIdentity, Coveo.CloudPlatformClient" />
      </getSearchUserIdentities>
    </pipelines>
  </sitecore>
</configuration>